train_set: /home/shi/data/data_v3/anns/referit/trainval.json
evaluate_set: /home/shi/data/data_v3/anns/referit/test.json

seg_gt_path: /home/shi/data/data_v3/masks/referit
image_path: /home/shi/data/images/referit/images



